### PR TITLE
Update to v0.14.0-rc3 (and CI test)

### PR DESCRIPTION
**Pull request by JordanMartinez**
Supercedes #8

Backlinking to purescript/purescript#3942

### CODE REVIEW

**Comment by JordanMartinez** [comment]
This library is blocking `gen` and `lists`, which are blocking pretty much everything else

**Comment by JordanMartinez** [comment]
CI passes. Can I get a review?

**Review by thomashoneyman — APPROVED** [review]

**Review by garyb — APPROVED** [review]

**Comment by garyb** [comment]
Oh, looks like I was too slow 😄

**Comment by thomashoneyman** [comment]
What are the odds? 😂

**Comment by JordanMartinez** [comment]
Thanks y'all!

**Pull request merged**
